# frozen_string_literal: true

# Domain kernel for "Autenticación JWT y Creación de Pedidos en Rails 7 API" (generated by gherkin-ai).
# Pure domain logic: no framework, no I/O. Extend the command handlers with your business rules.
class AutenticacionJwtYCreacionDePedidosEnRails7ApiAggregate
  STATES = %w[PENDING].freeze
  EVENT_TYPES = %w[ProcessAutenticacionJwtYCreacionDePedidosEnRails7ApiCompleted AutenticacionJwtYCreacionDePedidosEnRails7ApiProcessed].freeze

  attr_reader :id, :state, :version

  def initialize(id)
    raise DomainValidationError, "AutenticacionJwtYCreacionDePedidosEnRails7Api id is required" if id.to_s.strip.empty?

    @id = id
    @state = "PENDING"
    @version = 0
    @pending_events = []
  end

  # Events recorded since the aggregate was loaded (to be saved via the outbox).
  def pending_events
    @pending_events.dup
  end

  def process_autenticacion_jwt_y_creacion_de_pedidos_en_rails7_api(command)
    assert_valid!(command)
    record("ProcessAutenticacionJwtYCreacionDePedidosEnRails7ApiCompleted", command.payload)
  end

  private

  def assert_valid!(command)
    raise DomainValidationError, 'Command id is required' if command.nil? || command.id.to_s.strip.empty?
    raise DomainValidationError, "Command targets #{command.id}, not #{id}" unless command.id == id
  end

  def record(type, payload)
    @version += 1
    event = AutenticacionJwtYCreacionDePedidosEnRails7ApiDomainEvent.new(type: type, aggregate_id: id, version: @version, occurred_on: Time.now.utc, payload: payload || {})
    @pending_events << event
    event
  end
end
