# Step definitions for "Autenticación JWT y Creación de Pedidos en Rails 7 API" (generated by gherkin-ai): wired to the feature, pending until implemented.

Before do
  @aggregate = AutenticacionJwtYCreacionDePedidosEnRails7ApiAggregate.new("scenario-aggregate")
end

Given(/^que un cliente realiza POST a `\/api\/v1\/users\/sign_in` con credenciales válidas$/) do
  # Pending: drive @aggregate (or the HTTP API) and assert the outcome.
  pending
end

Then(/^Rails API responde con HTTP 200 y el Header `Authorization: Bearer <jwt_token>`$/) do
  # Pending: drive @aggregate (or the HTTP API) and assert the outcome.
  pending
end

When(/^el cliente React envía POST a `\/api\/v1\/orders` adjuntando el Bearer Token$/) do
  # Pending: drive @aggregate (or the HTTP API) and assert the outcome.
  pending
end

Then(/^el `Api::V1::OrdersController` ejecuta el `CreateOrderService`$/) do
  # Pending: drive @aggregate (or the HTTP API) and assert the outcome.
  pending
end

Then(/^RSpec valida que la transacción y la auditoría se persistan correctamente$/) do
  # Pending: drive @aggregate (or the HTTP API) and assert the outcome.
  pending
end
