/* ==========================================================================
   Generated Test Fixtures & Seed Setup
   Feature: Autenticación JWT y Creación de Pedidos en Rails 7 API
   Generated by gherkin-ai CLI
   ========================================================================== */

export interface AutenticacionJwtYCreacionDePedidosEnRails7ApiFixture {
  id: string;

}

export function createAutenticacionJwtYCreacionDePedidosEnRails7ApiFixture(): AutenticacionJwtYCreacionDePedidosEnRails7ApiFixture {
  return {
    id: 'f47ac10b-58cc-4372-a567-0e02b2c3d479',

  };
}

export const GHERKIN_GIVEN_PRECONDITIONS = [
  "que un cliente realiza POST a `/api/v1/users/sign_in` con credenciales válidas"
];
