source "https://rubygems.org"

ruby ">= 3.2"

gem "rails", "~> 8.0.0"
gem "puma", ">= 6.0"
gem "pg", "~> 1.5"
gem "bunny", "~> 2.23"
gem "opentelemetry-sdk", "~> 1.5"

group :development, :test do
  gem "rspec-rails", "~> 7.1"
end

group :test do
  gem "cucumber", "~> 9.2"
  gem "rack-test", "~> 2.1"
end
